import { AllowedPolicy, DeniedPolicy, GroupsPolicy, PatternsPolicy, ScopesPolicy } from './types.js';

export const DEFAULT_ALLOWED_POLICY: AllowedPolicy = {
  spacing: {
    layout: ['0', '2', '4', '6', '8', '10', '12', '16', '20', '24'],
    control: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '10', '12'],
  },
  utilities: [
    'block',
    'inline',
    'inline-block',
    'inline-flex',
    'flex',
    'grid',
    'hidden',
    'relative',
    'absolute',
    'fixed',
    'sticky',
    'static',
    'sr-only',
    'not-sr-only',
    'container',
    'mx-auto',
    'w-full',
    'w-auto',
    'w-fit',
    'w-screen',
    'h-full',
    'h-auto',
    'h-fit',
    'h-screen',
    'min-w-0',
    'max-w-none',
    'max-w-sm',
    'max-w-md',
    'max-w-lg',
    'max-w-xl',
    'max-w-2xl',
    'max-w-3xl',
    'max-w-4xl',
    'max-w-5xl',
    'max-w-6xl',
    'max-w-7xl',
    'overflow-hidden',
    'overflow-auto',
    'overflow-visible',
    'overflow-scroll',
    'object-cover',
    'object-contain',
    'object-fill',
    'object-center',
    'object-top',
    'object-bottom',
    'aspect-auto',
    'aspect-square',
    'aspect-video',
    'truncate',
    'whitespace-nowrap',
    'rounded',
    'rounded-none',
    'rounded-sm',
    'rounded-md',
    'rounded-lg',
    'rounded-xl',
    'rounded-2xl',
    'rounded-3xl',
    'rounded-full',
    'shadow',
    'shadow-none',
    'shadow-sm',
    'shadow-md',
    'shadow-lg',
    'shadow-xl',
    'border',
    'border-0',
    'border-2',
    'border-4',
    'border-border',
    'bg-background',
    'bg-card',
    'bg-muted',
    'bg-primary',
    'bg-secondary',
    'bg-destructive',
    'bg-accent',
    'bg-transparent',
    'text-foreground',
    'text-muted-foreground',
    'text-primary',
    'text-primary-foreground',
    'text-secondary',
    'text-secondary-foreground',
    'text-destructive',
    'text-destructive-foreground',
    'text-accent-foreground',
    'text-card-foreground',
    'text-xs',
    'text-sm',
    'text-base',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-4xl',
    'text-5xl',
    'font-normal',
    'font-medium',
    'font-semibold',
    'font-bold',
    'leading-none',
    'leading-tight',
    'leading-normal',
    'leading-relaxed',
    'tracking-tight',
    'tracking-normal',
    'tracking-wide',
    'text-left',
    'text-center',
    'text-right',
    'text-justify',
    'flex-row',
    'flex-col',
    'flex-wrap',
    'flex-nowrap',
    'grow',
    'grow-0',
    'shrink',
    'shrink-0',
    'items-start',
    'items-center',
    'items-end',
    'items-stretch',
    'justify-start',
    'justify-center',
    'justify-end',
    'justify-between',
    'justify-around',
    'justify-evenly',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-4',
    'grid-cols-5',
    'grid-cols-6',
    'grid-cols-12',
  ],
};

export const DEFAULT_DENIED_POLICY: DeniedPolicy = {
  utilities: {
    'bg-red-500': {
      reason: 'Use semantic color tokens instead of raw palette colors.',
      suggest: ['bg-destructive'],
    },
    'text-red-500': {
      reason: 'Use semantic color tokens instead of raw palette colors.',
      suggest: ['text-destructive'],
    },
  },
};

export const DEFAULT_SCOPES_POLICY: ScopesPolicy = {
  defaultScope: 'layout',
  scopes: [
    {
      name: 'controls',
      files: ['src/ui/**', 'src/components/**', 'ui/**', 'components/**'],
      spacing: 'control',
    },
    {
      name: 'layout',
      files: ['src/views/**', 'src/pages/**', 'examples/**', 'internal/site/views/**'],
      spacing: 'layout',
    },
  ],
};

export const DEFAULT_GROUPS_POLICY: GroupsPolicy = {
  conflictGroups: {
    display: ['block', 'inline', 'inline-block', 'inline-flex', 'flex', 'grid', 'hidden'],
    flexDirection: ['flex-row', 'flex-col', 'flex-row-reverse', 'flex-col-reverse'],
    flexWrap: ['flex-wrap', 'flex-nowrap'],
    items: ['items-*'],
    justify: ['justify-*'],
    textSize: ['text-xs', 'text-sm', 'text-base', 'text-lg', 'text-xl', 'text-2xl', 'text-3xl', 'text-4xl', 'text-5xl'],
    textAlign: ['text-left', 'text-center', 'text-right', 'text-justify'],
    background: ['bg-*'],
    radius: ['rounded', 'rounded-*'],
    shadow: ['shadow', 'shadow-*'],
  },
};

export const DEFAULT_PATTERNS_POLICY: PatternsPolicy = {
  patterns: {},
};
