/* Generated by ui8px brand OS emitter. */
export const techBrandTailwindExtend = {
  fontFamily: {
    "display": ["Merriweather", "Georgia", "serif"],
    "ui": ["Inter", "system-ui", "sans-serif"],
    "mono": ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "monospace"],
  },
  colors: {
    "background": "hsl(var(--background))",
    "foreground": "hsl(var(--foreground))",
    "card": {
      DEFAULT: "hsl(var(--card))",
      foreground: "hsl(var(--card-foreground))",
    },
    "popover": {
      DEFAULT: "hsl(var(--popover))",
      foreground: "hsl(var(--popover-foreground))",
    },
    "primary": {
      DEFAULT: "hsl(var(--primary))",
      foreground: "hsl(var(--primary-foreground))",
    },
    "secondary": {
      DEFAULT: "hsl(var(--secondary))",
      foreground: "hsl(var(--secondary-foreground))",
    },
    "muted": {
      DEFAULT: "hsl(var(--muted))",
      foreground: "hsl(var(--muted-foreground))",
    },
    "accent": {
      DEFAULT: "hsl(var(--accent))",
      foreground: "hsl(var(--accent-foreground))",
    },
    "destructive": {
      DEFAULT: "hsl(var(--destructive))",
      foreground: "hsl(var(--destructive-foreground))",
    },
    "border": "hsl(var(--border))",
    "input": "hsl(var(--input))",
    "ring": "hsl(var(--ring))",
    "success": {
      DEFAULT: "hsl(var(--success))",
      foreground: "hsl(var(--success-foreground))",
    },
    "warning": {
      DEFAULT: "hsl(var(--warning))",
      foreground: "hsl(var(--warning-foreground))",
    },
    "info": {
      DEFAULT: "hsl(var(--info))",
      foreground: "hsl(var(--info-foreground))",
    },
    "promo": {
      DEFAULT: "hsl(var(--promo))",
      foreground: "hsl(var(--promo-foreground))",
    },
    "surface-elevated": "hsl(var(--surface-elevated))",
    "surface-subtle": "hsl(var(--surface-subtle))",
    "surface-strong": "hsl(var(--surface-strong))",
    "cream": {
      DEFAULT: "hsl(var(--cream))",
      foreground: "hsl(var(--cream-foreground))",
    },
    "overlay-soft": "hsl(var(--overlay-soft))",
    "overlay-strong": "hsl(var(--overlay-strong))",
    "shadow-soft": "hsl(var(--shadow-soft))",
    "category-1": "hsl(var(--category-1))",
    "category-2": "hsl(var(--category-2))",
    "category-3": "hsl(var(--category-3))",
    "category-4": "hsl(var(--category-4))",
    "category-5": "hsl(var(--category-5))",
    "category-6": "hsl(var(--category-6))",
    "category-7": "hsl(var(--category-7))",
    "chart-1": "hsl(var(--chart-1))",
    "chart-2": "hsl(var(--chart-2))",
    "chart-3": "hsl(var(--chart-3))",
    "chart-4": "hsl(var(--chart-4))",
    "chart-5": "hsl(var(--chart-5))",
  },
  borderRadius: {
    "sm": "var(--radius-sm)",
    "md": "var(--radius-md)",
    "lg": "var(--radius-lg)",
    "xl": "var(--radius-xl)",
    "media": "var(--radius-media)",
    "shell": "var(--radius-shell)",
    "pill": "var(--radius-pill)",
  },
  boxShadow: {
    "none": "none",
    "soft": "0 4px 20px -4px hsl(var(--shadow-soft) / 0.10)",
    "elevated": "0 20px 40px -10px hsl(var(--shadow-soft) / 0.15)",
    "floating": "0 4px 12px -2px hsl(var(--shadow-soft) / 0.15)",
  },
  keyframes: {
    fadeIn: {
      from: { opacity: "0" },
      to: { opacity: "1" },
    },
    slideUp: {
      from: { opacity: "0", transform: "translateY(20px)" },
      to: { opacity: "1", transform: "translateY(0)" },
    },
    slideDown: {
      from: { opacity: "0", transform: "translateY(-20px)" },
      to: { opacity: "1", transform: "translateY(0)" },
    },
    scaleIn: {
      from: { opacity: "0", transform: "scale(0.95)" },
      to: { opacity: "1", transform: "scale(1)" },
    },
  },
  animation: {
    "fade-in": "fadeIn 0.5s ease-out",
    "slide-up": "slideUp 0.6s ease-out",
    "slide-down": "slideDown 0.6s ease-out",
    "scale-in": "scaleIn 0.5s ease-out",
  },
} as const;

export default techBrandTailwindExtend;
